# © Copyright IBM Corporation 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- include "sch.config.init" (list . "ibm-ace.sch.chart.config.values") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sch.names.fullName" (list .) }}
  labels:
{{ include "sch.metadata.labels.standard" (list . "") | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.webuiPort }}
    targetPort: {{ .Values.service.webuiPort }}
    protocol: TCP
    name: webui
  - port: {{ .Values.service.serverlistenerPort }}
    targetPort: {{ .Values.service.serverlistenerPort }}
    protocol: TCP
    name: ace-http
  - port: {{ .Values.service.serverlistenerTLSPort }}
    targetPort: {{ .Values.service.serverlistenerTLSPort }}
    protocol: TCP
    name: ace-https
  - port: {{ .Values.service.switch1 }}
    targetPort: {{ .Values.service.switch1 }}
    protocol: TCP
    name: switch1
  - port: {{ .Values.service.switch2 }}
    targetPort: {{ .Values.service.switch2 }}
    protocol: TCP
    name: switch2
  - port: {{ .Values.service.switch3 }}
    targetPort: {{ .Values.service.switch3 }}
    protocol: TCP
    name: switch3
  - port: {{ .Values.service.gclistener }}
    targetPort: {{ .Values.service.gclistener }}
    protocol: TCP
    name: gclistener
  - port: {{ .Values.service.gcclient }}
    targetPort: {{ .Values.service.gcclient }}
    protocol: TCP
    name: gcclient
  - port: {{ .Values.service.gcjmx }}
    targetPort: {{ .Values.service.gcjmx }}
    protocol: TCP
    name: gcjmx
  - port: {{ .Values.service.gcha }}
    targetPort: {{ .Values.service.gcha }}
    protocol: TCP
    name: gcha
  {{- if .Values.queueManagerEnabled }}
  - port: 1414
    targetPort: 1414
    protocol: TCP
    name: qmgr
  {{- end }}
  selector:
    app: "{{ include "sch.names.appName" (list .) }}"
    release: "{{ .Release.Name }}"
