image:
  repository:
    acemq: mycluster.icp:8500/icp4i/ace/ibm-ace-mq-server-prod
    configurator: mycluster.icp:8500/icp4i/ace/ibm-ace-icp-configurator-prod
  pullPolicy: Always
  pullSecret: hyc-icpcontent-docker-local.artifactory.swg-devops.com
license: accept
queueManagerEnabled: true
acemq:
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 1
      memory: 1024Mi
configurationSecret: test03-secret
service:
  type: NodePort
log:
  format: basic
